development:
  adapter: mysql2
  database: bim
  username: root
  password:

test:
  adapter: mysql2
  database: bim
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: de619esfei863d
  pool: 5
  username: ifauyiwoesdopa
  password: tk34bkYJhmUlOUS-j3W35fnGkf
